title: Abolfazl Rahimnejad
description: Professional Academic and Research Website
author: Abolfazl Rahimnejad
email: a.rahimnejad@mcmaster.ca
url: https://AbRahimnejad.github.io
baseurl: ''
github_username: AbRa60
theme: jekyll-theme-minimal
markdown: kramdown
